# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'EJQLPreview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EJQLPreview
  pod 'EJWarningCardView'

  target 'EJQLPreviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EJQLPreviewUITests' do
    # Pods for testing
  end

end
